### ISSUE TITLE
accented  characters not supported 

### ISSUE THREAD

**Issue by geniusayush** [Weebly/cloud-client-java#3]
the sdk while setting the content in the body does not convert them into utf 8 
but while computing the hash does that.
as a result if the string has accented characters the hash ad the body has differnt strings hence we get invalid hash error.
i have corrected the same and created a pul request for the same

**Comment by bdeanindy** [comment]
Hello @geniusayush thank you for your patience. 

Just a quick update from us:

1. We have received your support request, and apologize for the delay in responding.
2. Our engineering team is investigating the issue.
3. Since this repository is open source software, we do welcome contributions via pull request. 👍

**Comment by geniusayush** [comment]
Thnks
Yeah I have tested the code and the pull request  I raised and it works fine
Please fix this asap as this is an urgent matter

On 16-Sep-2017 2:56 AM, "Benjamin Dean" <notifications@github.com> wrote:

Hello @geniusayush <https://github.com/geniusayush> thank you for your
patience.

Just a quick update from us:

   1. We have received your support request, and apologize for the delay in
   responding.
   2. Our engineering team is investigating the issue.
   3. Since this repository is open source software, we do welcome
   contributions via pull request. 👍

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Weebly/cloud-client-java/issues/3#issuecomment-329908184>,
or mute the thread

**Comment by bdeanindy** [comment]
Your PR was merged resolving this issue.

**Comment by geniusayush** [comment]
thnks
